### ISSUE TITLE
三个小bug

### ISSUE THREAD

**Issue by lixuancryo** [LittleSaya/IndexOutOfRangeDSPMod#10]
1.行星直径250，铺设地基时，显示的与鼠标指的位置不对。但是铺下去还是铺在鼠标点的地方。倒是不影响游戏。去在其他直径行星上没出现这个问题。但没有去另一个250直径的行星常试。
2.影子渲染不对。在特定的方向星际物流塔影子没了。只有这一个方向（范围，不是某个特定的角度）会没有，而且只有星际物流塔没有。直径仍然250
3.在有些行星上扔垃圾会往太空飞，直径大于200小于200都有。有的行星上不会飞，正常在地上（也是大于200小于200的都有）。没看出明显规律。

除了扔垃圾这个有一丢丢影响，其他两修不修都无所谓

![F51GQHCOTPUDG`4AK{JG@PL](https://user-images.githubusercontent.com/84318640/170022284-872353c4-ced2-43a0-884e-502070f38ab7.png)
![92_8IPBK{9JZ_8KY_4O~M{S](https://user-images.githubusercontent.com/84318640/170022558-1047b138-cbbc-417b-9728-67ca829e35ff.png)
![IMG_20220524_191855](https://user-images.githubusercontent.com/84318640/170023385-2e014428-f282-41c4-a2df-66551c034328.jpg)

[Uploading 存档.zip…]()
打开存档在原地转视角就能看见影子问题。所有星际物流站都会出问题。

**Comment by LittleSaya** [comment]
第一个问题已经发现了，目前正在研究第一个问题
第二个问题最好能提供一个案发现场的存档，我看见这个issue下面好像有个存档的连接，但是点开来还是这个issue，存档（包括配置文件）可以发给这个邮箱：littlesaya@outlook.com
第三个问题最好可以提供一下扔垃圾不正常的星球的配置字符串

**Comment by lixuancryo** [comment]
[存档.zip](https://github.com/LittleSaya/IndexOutOfRangeDSPMod/files/8764671/default.zip)

**Comment by LittleSaya** [comment]
> 再添加一个问题，依旧是就我发的这个档，就在这个戈壁星上。粘贴蓝图时，四项分流器都会报错说超出最大建筑高度。事实上这项科技已经升满了的。

好的，这个问题我也记下了

**Comment by lixuancryo** [comment]
紧急补充，这个戈壁星原为飓风石林。给其他行星设置theme参数后，它就变了。不知道这个有没有影响

**Comment by LittleSaya** [comment]
> 紧急补充，这个戈壁星原为飓风石林。给其他行星设置theme参数后，它就变了。不知道这个有没有影响

这个Mod是通过调用游戏原有的创建行星的方法来创建行星的，具体的逻辑我还没有进行深入的了解，不过先创建的行星好像会影响后创建的行星，行星是按配置文件里的顺序生成的，如果改了前面的行星（或者删了前面的行星），后面的行星可能会发生变化

**Comment by lixuancryo** [comment]
对。就怕我上面说的那些bug可能有部分是这个原因。比如影子和地基。

**Comment by LittleSaya** [comment]
地基的问题修复了一部分，现在在250半径的行星上应该不会偏离鼠标位置了，但是在预览地基时有概率出现好几个格子一起高亮的情况，问题原理我也没搞懂，不过应该只是视觉效果出错

影子那个问题我估计是投下阴影的那座物流塔刚好是被太阳水平照射的，阴影很长，但是物流塔的本体又在屏幕外面，游戏就把这个物流塔优化掉，不渲染了，然后阴影就跟着一起不渲染了

垃圾往上飘的问题也在新版本里修复了，更新之前建议先把存档备份一下

**Comment by lixuancryo** [comment]
好的~辛苦
