### ISSUE TITLE
[DSPTransportStat] 视窗开启时切换存档会报错

### ISSUE THREAD

**Issue by starfi5h** [LittleSaya/IndexOutOfRangeDSPMod#12]
![err](https://user-images.githubusercontent.com/50672801/170814026-758f0c78-6ad3-484f-9334-b60e51e6e6c1.jpg)
版本: 0.0.11
只要在换存档前关闭视窗就可以避免了

之前切换存档不能开启视窗的问题已经修复了, 感谢

**Comment by LittleSaya** [comment]
我上传了0.0.12版本，退出游戏前会自动关掉窗口，应该能解决这个问题
