### ISSUE TITLE
DSPAddPlanet - 大半径星球上蓝图粘贴可以堆叠的建筑提示超出最大建造等级

### ISSUE THREAD

**Issue by lixuancryo** [LittleSaya/IndexOutOfRangeDSPMod#13]
半径600，几乎可以堆叠放置的建筑都会提示超过最大等级。哪怕只建一个都会提示。只粘贴一个喷涂机不会提示，但是如果粘贴已经堆叠的喷涂机，会提示处在二层的喷涂机需要地基支撑。

**Comment by LittleSaya** [comment]
估计游戏对建筑高度+半径做了总的限制，我看看怎么把它改掉

**Comment by lixuancryo** [comment]
又遇到一个，我觉得是同一个原因造成的？
就是在小半径星球上（半径60），建造没有升高的传送带，在转弯时也会报“转弯不能升降”。

**Comment by LittleSaya** [comment]
半径600会提示“超出垂直建造高度”的问题应该在0.0.12版本修复了，“转弯不能升降”的问题我好像没有遇到，可以发个存档吗？

**Comment by lixuancryo** [comment]
已发邮件
