### ISSUE TITLE
DSPTransportStat - pressing ESC doesn't close mod window

### ISSUE THREAD

**Issue by mitasov-ra** [LittleSaya/IndexOutOfRangeDSPMod#14]
When I open the TransportStat window with a bunch of other game windows (e.g. inventory, crafting, fuel chamber) and consecutively press ESC, then all the game windows end up closed, except TransportStat.

If I continue to press ECS it will just pause the game. After unpause the TransportStat window remains opened.

**Comment by LittleSaya** [comment]
Yes, the window even persists between loadings (cause errors though) before

I will try to make it respond to ESC in next update

**Comment by LittleSaya** [comment]
Added in version 0.0.13
