### ISSUE TITLE
DSPAddPlanet - 小半径星球地基铺设

### ISSUE THREAD

**Issue by lixuancryo** [LittleSaya/IndexOutOfRangeDSPMod#16]
半径（125）在高纬度（极点附近），地基调大6x6，9x9这样的，就会报错
![W%EY(8CC~F2060RW {ZTYBA](https://user-images.githubusercontent.com/84318640/171032565-74d275ab-d3cb-4e74-ab82-7379a2a86b3e.png)
。

**Comment by LittleSaya** [comment]
0.0.12版本应该修复了这个问题，这个问题和半径250的时候是一样的，目前还不清楚具体原理，只能遇到一个修复一个
