### ISSUE TITLE
DSPTransportStat - TargetException on drag&drop items from storage

### ISSUE THREAD

**Issue by mitasov-ra** [LittleSaya/IndexOutOfRangeDSPMod#18]
![image](https://user-images.githubusercontent.com/29340679/171225748-902f401d-1324-4919-9d08-1d41e71b459f.png)

Steps to reproduce:
1. Open small storage
2. Shift+click on items

**Comment by LittleSaya** [comment]
It's weird that I can not trigger this error steadily, I tried many times and only once successfully triggered this error. Can you trigger this error steadily?

Anyway, I uploaded a new version which will avoid this exception.

**Comment by mitasov-ra** [comment]
> I tried many times and only once successfully triggered this error

same
