### ISSUE TITLE
DSPTransportStat - 不能拿取或点击行星运输站

### ISSUE THREAD

**Issue by SimarSima** [LittleSaya/IndexOutOfRangeDSPMod#19]

**Comment by SimarSima** [comment]
> 请提供复现问题的详细步骤
有两个情况：
1. 点击打开行星运输站#29 ，但打开的是行星运输站#9
2. 到行星运输站，点击行星运输站没有反应

p.s
我还安装的Mod 有：MoreStatInfo，Auxilaryfunction，RailgunsRetargeting，Bottleneck，DSPOptimizations

万分感谢大佬的Mod
Save my life

**Comment by LittleSaya** [comment]
新版本应该修复了这两个问题

**Comment by SimarSima** [comment]
好用了，感谢。
