### ISSUE TITLE
DSPAddPlanet - 求求大佬快更新吧！

### ISSUE THREAD

**Issue by lixuancryo** [LittleSaya/IndexOutOfRangeDSPMod#23]
求求大佬适配新版本吧~想玩想疯了呀~~呜呜呜呜呜
谢谢谢谢谢谢谢谢谢！

**Comment by LittleSaya** [comment]
有点奇怪，我发现更新以后把mod全卸了打开游戏还是出红框，还在排查

**Comment by lixuancryo** [comment]
啊，我没有这个情况呢

**Comment by LittleSaya** [comment]
0.1.1版本应该能正常加载游戏了

**Comment by lixuancryo** [comment]
请问一下，这个xml怎么编辑啊？用记事本吗？

**Comment by LittleSaya** [comment]
> 请问一下，这个xml怎么编辑啊？用记事本吗？

记事本可以，其他随便什么文本编辑器应该都行

**Comment by lixuancryo** [comment]
<Config>
    <Planet>
        <UniqueStarId>hard-43913797-64-A01-Alya</UniqueStarId>
        <Index>4</Index>
        <OrbitAround>1</OrbitAround>
        <OrbitIndex>3</OrbitIndex>
        <Number>5</Number>
        <GasGiant>false</GasGiant>
        <InfoSeed>0</InfoSeed>
        <GenSeed>0</GenSeed>
        <ForcePlanetRadius>false</ForcePlanetRadius>
        <Radius>200</Radius>
        <OrbitalPeriod>954</OrbitalPeriod>
        <RotationPeriod>425</RotationPeriod>
        <IsTidalLocked>false</IsTidalLocked>
        <OrbitInclination>4</OrbitInclination>
        <Obliquity>2</Obliquity>
        <DontGenerateVein>true</DontGenerateVein>
        <ThemeId>17</ThemeId>
        <OrbitLongitude>44</OrbitLongitude>
        <VeinCustom>
            <Mag>
                <VeinGroupCount>
                    <Type>Accurate</Type>
                    <AccurateValue>5</AccurateValue>
                </VeinGroupCount>
                <VeinSpotCount>
                    <Type>Random</Type>
                    <RandomBaseValue>1000</RandomBaseValue>
                    <RandomCoef>1</RandomCoef>
                    <RandomMulOffset>0</RandomMulOffset>
                    <RandomAddOffset>5</RandomAddOffset>
                </VeinSpotCount>
                <VeinAmount>
                    <Type>Default</Type>
                </VeinAmount>
            </Mag>
        </VeinCustom>
    </Planet>
</Config>

那这个怎么不行呢？

**Comment by lixuancryo** [comment]
<Config>
    <Planet>
        <UniqueStarId>hard-43913797-64-A01-Alya</UniqueStarId>
        <Index>4</Index>
        <OrbitAround>1</OrbitAround>
        <OrbitIndex>3</OrbitIndex>
        <Number>5</Number>
        <GasGiant>false</GasGiant>
        <InfoSeed>0</InfoSeed>
        <GenSeed>0</GenSeed>
        <ForcePlanetRadius>false</ForcePlanetRadius>
        <Radius>200</Radius>
        <OrbitalPeriod>954</OrbitalPeriod>
        <RotationPeriod>425</RotationPeriod>
        <IsTidalLocked>false</IsTidalLocked>
        <OrbitInclination>4</OrbitInclination>
        <Obliquity>2</Obliquity>
        <DontGenerateVein>true</DontGenerateVein>
        <ThemeId>17</ThemeId>
        <OrbitLongitude>44</OrbitLongitude>
        <VeinCustom>
            <Mag>
                <VeinGroupCount>
                    <Type>Accurate</Type>
                    <AccurateValue>5</AccurateValue>
                </VeinGroupCount>
                <VeinSpotCount>
                    <Type>Random</Type>
                    <RandomBaseValue>1000</RandomBaseValue>
                    <RandomCoef>1</RandomCoef>
                    <RandomMulOffset>0</RandomMulOffset>
                    <RandomAddOffset>5</RandomAddOffset>
                </VeinSpotCount>
                <VeinAmount>
                    <Type>Default</Type>
                </VeinAmount>
            </Mag>
        </VeinCustom>
    </Planet>
</Config>

**Comment by lixuancryo** [comment]
![image](https://user-images.githubusercontent.com/84318640/173195532-9e4290bf-eb27-468b-bdf9-ef2cc7e59328.png)
这个咋不行呢

**Comment by LittleSaya** [comment]
> ![image](https://user-images.githubusercontent.com/84318640/173195532-9e4290bf-eb27-468b-bdf9-ef2cc7e59328.png) 这个咋不行呢

看上去好像没有问题，可以把文本粘贴在这里吗，我进游戏瞅瞅

**Comment by lixuancryo** [comment]
粘上去就变了
<Config>
    <Planet>
        <UniqueStarId>hard-43913797-64-A01-Alya</UniqueStarId>
        <Index>4</Index>
        <OrbitAround>1</OrbitAround>
        <OrbitIndex>3</OrbitIndex>
        <Number>5</Number>
        <GasGiant>false</GasGiant>
        <InfoSeed>0</InfoSeed>
        <GenSeed>0</GenSeed>
        <ForcePlanetRadius>false</ForcePlanetRadius>
        <Radius>200</Radius>
        <OrbitalPeriod>954</OrbitalPeriod>
        <RotationPeriod>425</RotationPeriod>
        <IsTidalLocked>false</IsTidalLocked>
        <OrbitInclination>4</OrbitInclination>
        <Obliquity>2</Obliquity>
        <DontGenerateVein>true</DontGenerateVein>
        <ThemeId>17</ThemeId>
        <OrbitLongitude>44</OrbitLongitude>
        <VeinCustom>
            <Mag>
                <VeinGroupCount>
                    <Type>Accurate</Type>
                    <AccurateValue>5</AccurateValue>
                </VeinGroupCount>
                <VeinSpotCount>
                    <Type>Random</Type>
                    <RandomBaseValue>1000</RandomBaseValue>
                    <RandomCoef>1</RandomCoef>
                    <RandomMulOffset>0</RandomMulOffset>
                    <RandomAddOffset>5</RandomAddOffset>
                </VeinSpotCount>
                <VeinAmount>
                    <Type>Default</Type>
                </VeinAmount>
            </Mag>
        </VeinCustom>
    </Planet>
</Config>

**Comment by lixuancryo** [comment]
[新建文件夹.zip](https://github.com/LittleSaya/IndexOutOfRangeDSPMod/files/8884313/default.zip)

**Comment by LittleSaya** [comment]
> [新建文件夹.zip](https://github.com/LittleSaya/IndexOutOfRangeDSPMod/files/8884313/default.zip)

<Config>是根标签，只能有一个，多个星球的话写多个<Planet>标签

```xml
<Config>
    <Planet>
        <UniqueStarId>hard-43913797-64-A01-Alya</UniqueStarId>
        <Index>4</Index>
        <OrbitAround>1</OrbitAround>
        <OrbitIndex>3</OrbitIndex>
        <Number>5</Number>
        <GasGiant>false</GasGiant>
        <InfoSeed>0</InfoSeed>
        <GenSeed>0</GenSeed>
        <ForcePlanetRadius>false</ForcePlanetRadius>
        <Radius>200</Radius>
        <OrbitalPeriod>954</OrbitalPeriod>
        <RotationPeriod>425</RotationPeriod>
        <IsTidalLocked>false</IsTidalLocked>
        <OrbitInclination>4</OrbitInclination>
        <Obliquity>2</Obliquity>
        <DontGenerateVein>true</DontGenerateVein>
        <ThemeId>17</ThemeId>
        <OrbitLongitude>44</OrbitLongitude>
        <VeinCustom>
            <Mag>
                <VeinGroupCount>
                    <Type>Accurate</Type>
                    <AccurateValue>5</AccurateValue>
                </VeinGroupCount>
                <VeinSpotCount>
                    <Type>Random</Type>
                    <RandomBaseValue>1000</RandomBaseValue>
                    <RandomCoef>1</RandomCoef>
                    <RandomMulOffset>0</RandomMulOffset>
                    <RandomAddOffset>5</RandomAddOffset>
                </VeinSpotCount>
                <VeinAmount>
                    <Type>Default</Type>
                </VeinAmount>
            </Mag>
        </VeinCustom>
    </Planet>
    <Planet>
        <UniqueStarId>hard-43913797-64-A01-Alya</UniqueStarId>
        <Index>5</Index>
        <OrbitAround>1</OrbitAround>
        <OrbitIndex>4</OrbitIndex>
        <Number>6</Number>
        <GasGiant>false</GasGiant>
        <InfoSeed>0</InfoSeed>
        <GenSeed>0</GenSeed>
        <ForcePlanetRadius>false</ForcePlanetRadius>
        <Radius>200</Radius>
        <OrbitalPeriod>1023</OrbitalPeriod>
        <RotationPeriod>225</RotationPeriod>
        <IsTidalLocked>false</IsTidalLocked>
        <OrbitInclination>12</OrbitInclination>
        <Obliquity>80</Obliquity>
        <DontGenerateVein>true</DontGenerateVein>
        <ThemeId>18</ThemeId>
        <OrbitLongitude>44</OrbitLongitude>
    </Planet>
</Config>
```

**Comment by lixuancryo** [comment]
ooo  可以了。谢谢~
还有一件事，theme id 好像不对

**Comment by LittleSaya** [comment]
> ooo 可以了。谢谢~ 还有一件事，theme id 好像不对

白色海洋其实就是樱林海，红土荒漠其实就是黑石盐滩，不知道为啥我从游戏里导出来的中文和实际游戏里显示的中文不一样。。

**Comment by lixuancryo** [comment]
哈哈哈好的～谢谢
