### ISSUE TITLE
DSPAddPlanet - 部分矿物无法正常生成？

### ISSUE THREAD

**Issue by lixuancryo** [LittleSaya/IndexOutOfRangeDSPMod#24]
不知道是不是我的原因。

**Comment by LittleSaya** [comment]
是昨天更新后产生的问题吗？是否可以给一个具体的例子

**Comment by lixuancryo** [comment]
刺笋和金伯利，设置了也生成不了。没有设置光栅石，光栅石却生成了。好像更新改了矿物的啥啥名称导致的，我也不是很懂。

**Comment by lixuancryo** [comment]
`   <Planet>
        <UniqueStarId>perfectid-61683540-64-A01-HR 0861</UniqueStarId>
        <Index>3</Index>
        <OrbitAround>0</OrbitAround>
        <OrbitIndex>16</OrbitIndex>
        <Number>4</Number>
        <GasGiant>false</GasGiant>
        <InfoSeed>0</InfoSeed>
        <GenSeed>0</GenSeed>
        <ForcePlanetRadius>false</ForcePlanetRadius>
        <Radius>200</Radius>
        <OrbitalPeriod>135</OrbitalPeriod>
        <RotationPeriod>33</RotationPeriod>
        <IsTidalLocked>true</IsTidalLocked>
        <OrbitInclination>0</OrbitInclination>
        <Obliquity>0</Obliquity>
        <DontGenerateVein>false</DontGenerateVein>
        <ThemeId>13</ThemeId>
        <OrbitLongitude>45</OrbitLongitude>
        <VeinCustom>
            <Mag>
                <VeinGroupCount>
                    <Type>Random</Type>
                </VeinGroupCount>
                <VeinSpotCount>
                    <Type>Accurate</Type>
                    <AccurateValue>1</AccurateValue>
                </VeinSpotCount>
                <VeinAmount>
                    <Type>Random</Type>
                    <RandomBaseValue>4000</RandomBaseValue>
                    <RandomCoef>1</RandomCoef>
                    <RandomMulOffset>0</RandomMulOffset>
                    <RandomAddOffset>5</RandomAddOffset>
                </VeinAmount>
            </Mag>
            <Fireice>
                <VeinGroupCount>
                    <Type>Random</Type>
                </VeinGroupCount>
                <VeinSpotCount>
                    <Type>Accurate</Type>
                    <AccurateValue>1</AccurateValue>
                </VeinSpotCount>
                <VeinAmount>
                    <Type>Random</Type>
                    <RandomBaseValue>4000</RandomBaseValue>
                    <RandomCoef>1</RandomCoef>
                    <RandomMulOffset>0</RandomMulOffset>
                    <RandomAddOffset>5</RandomAddOffset>
                </VeinAmount>
            </Fireice>
            <Diamond>
                <VeinGroupCount>
                    <Type>Random</Type>
                </VeinGroupCount>
                <VeinSpotCount>
                    <Type>Accurate</Type>
                    <AccurateValue>1</AccurateValue>
                </VeinSpotCount>
                <VeinAmount>
                    <Type>Random</Type>
                    <RandomBaseValue>4000</RandomBaseValue>
                    <RandomCoef>1</RandomCoef>
                    <RandomMulOffset>0</RandomMulOffset>
                    <RandomAddOffset>5</RandomAddOffset>
                </VeinAmount>
            </Diamond>
            <Fractal>
                <VeinGroupCount>
                    <Type>Random</Type>
                </VeinGroupCount>
                <VeinSpotCount>
                    <Type>Accurate</Type>
                    <AccurateValue>1</AccurateValue>
                </VeinSpotCount>
                <VeinAmount>
                    <Type>Random</Type>
                    <RandomBaseValue>4000</RandomBaseValue>
                    <RandomCoef>1</RandomCoef>
                    <RandomMulOffset>0</RandomMulOffset>
                    <RandomAddOffset>5</RandomAddOffset>
                </VeinAmount>
            </Fractal>
            <Crysrub>
                <VeinGroupCount>
                    <Type>Random</Type>
                </VeinGroupCount>
                <VeinSpotCount>
                    <Type>Accurate</Type>
                    <AccurateValue>1</AccurateValue>
                </VeinSpotCount>
                <VeinAmount>
                    <Type>Random</Type>
                    <RandomBaseValue>4000</RandomBaseValue>
                    <RandomCoef>1</RandomCoef>
                    <RandomMulOffset>0</RandomMulOffset>
                    <RandomAddOffset>5</RandomAddOffset>
                </VeinAmount>
            </Crysrub>
            <Grat>
                <VeinGroupCount>
                    <Type>Random</Type>
                </VeinGroupCount>
                <VeinSpotCount>
                    <Type>Accurate</Type>
                    <AccurateValue>1</AccurateValue>
                </VeinSpotCount>
                <VeinAmount>
                    <Type>Random</Type>
                    <RandomBaseValue>4000</RandomBaseValue>
                    <RandomCoef>1</RandomCoef>
                    <RandomMulOffset>0</RandomMulOffset>
                    <RandomAddOffset>5</RandomAddOffset>
                </VeinAmount>
            </Grat>
            <Bamboo>
                <VeinGroupCount>
                    <Type>Random</Type>
                </VeinGroupCount>
                <VeinSpotCount>
                    <Type>Accurate</Type>
                    <AccurateValue>1</AccurateValue>
                </VeinSpotCount>
                <VeinAmount>
                    <Type>Random</Type>
                    <RandomBaseValue>4000</RandomBaseValue>
                    <RandomCoef>1</RandomCoef>
                    <RandomMulOffset>0</RandomMulOffset>
                    <RandomAddOffset>5</RandomAddOffset>
                </VeinAmount>
            </Bamboo>
        </VeinCustom>
    </Planet>`
![1655561033751](https://user-images.githubusercontent.com/84318640/174442007-b0cc2957-48a9-4792-8507-aa9fde9a5e5f.jpg)

**Comment by LittleSaya** [comment]
我上传了一个新的版本，应该能正常兼容新版本的游戏了，另外添加了一些新功能，配置文件的格式变了，注意按新的说明文档调整配置文件的格式

**Comment by lixuancryo** [comment]
ok   辛苦
