### ISSUE TITLE
index询问

### ISSUE THREAD

**Issue by lixuancryo** [LittleSaya/IndexOutOfRangeDSPMod#25]
globle里往一个恒星系里加了一个星球，假设这个球的index是3，之后在specific里继续往这个星系加星球，index是4吗？ 
能许愿一个 给类地行星添加卫星的功能吗？(⌇ຶД⌇ຶ)

**Comment by LittleSaya** [comment]
还是3

`Global`和`GameNameSpecific`里的配置不会相互干扰

游戏里的行星是一组一组生成的，一个恒星周围的行星为一组，每组行星在生成之前都会考虑是使用`Global`里的配置还是使用`GameNameSpecific`里的配置，如果`GameNameSpecific`里存在这个恒星的配置，那么在生成这组行星时，mod就只会考虑`GameNameSpecific`里这个恒星的配置，哪怕`Global`里存在`GameNameSpecific`里没有出现的行星，也不会被考虑到，目前还没有细致到能够控制单个行星

新游戏始终只会考虑`Global`里的配置，因为新游戏没有`GameName`

已经存过档的游戏会优先考虑`GameNameSpecific`里的配置，其次考虑`Global`里的

**Comment by LittleSaya** [comment]
我试试看能不能给非气态的行星添加卫星

**Comment by LittleSaya** [comment]
应该可以给普通行星加卫星啊，我试了一下，只要把OrbitAround设置成需要围绕的行星的Number就可以

![20220702163221_1](https://user-images.githubusercontent.com/16049823/176993346-7c9bb46e-7e23-463c-b9b4-0ebac6203648.jpg)

**Comment by lixuancryo** [comment]
> 还是3
> 
> `Global`和`GameNameSpecific`里的配置不会相互干扰
> 
> 游戏里的行星是一组一组生成的，一个恒星周围的行星为一组，每组行星在生成之前都会考虑是使用`Global`里的配置还是使用`GameNameSpecific`里的配置，如果`GameNameSpecific`里存在这个恒星的配置，那么在生成这组行星时，mod就只会考虑`GameNameSpecific`里这个恒星的配置，哪怕`Global`里存在`GameNameSpecific`里没有出现的行星，也不会被考虑到，目前还没有细致到能够控制单个行星
> 
> 新游戏始终只会考虑`Global`里的配置，因为新游戏没有`GameName`
> 
> 已经存过档的游戏会优先考虑`GameNameSpecific`里的配置，其次考虑`Global`里的

哦哦哦好的！全明白了。谢谢！

**Comment by lixuancryo** [comment]
> 应该可以给普通行星加卫星啊，我试了一下，只要把OrbitAround设置成需要围绕的行星的Number就可以
> 
> ![20220702163221_1](https://user-images.githubusercontent.com/16049823/176993346-7c9bb46e-7e23-463c-b9b4-0ebac6203648.jpg)

对（捂脸），后来我自己试了一下发现居然可以了。不知道哪个版本开始可以的，最开始都不行的哇。
