### ISSUE TITLE
救命哇~求适配

### ISSUE THREAD

**Issue by lixuancryo** [LittleSaya/IndexOutOfRangeDSPMod#29]

**Comment by lixuancryo** [comment]
游戏更新了;_;

**Comment by LittleSaya** [comment]
我周末更新一下版本😂，战斗系统没更新最近都没啥动力玩了😭

**Comment by LittleSaya** [comment]
应该适配新的版本了

**Comment by lixuancryo** [comment]
感谢~

**Comment by lixuancryo** [comment]
呜呜呜呜呜咋回事啊，满心欢喜打开游戏。进不去哇

**Comment by lixuancryo** [comment]
![微信图片_20221107225527](https://user-images.githubusercontent.com/84318640/200341361-e5b8d857-38eb-40d3-a17a-fd164cf16635.jpg)

**Comment by LittleSaya** [comment]
@lixuancryo 发一下配置文件我瞅瞅

**Comment by lixuancryo** [comment]
[config.txt](https://github.com/LittleSaya/IndexOutOfRangeDSPMod/files/9957273/config.txt)

**Comment by LittleSaya** [comment]
@lixuancryo 新的版本应该修复了这个问题
