### ISSUE TITLE
DSPTransportStat MOD失效，别的mod正常运行

### ISSUE THREAD

**Issue by NAGATOYUKl** [LittleSaya/IndexOutOfRangeDSPMod#31]
通过R2modman启动mod，尝试过只单独启用该mod (均重开了管理器)，也依旧无效（通过快捷键）。
翻了下记录，不知道如何导出日志，请教一下，我后续会补充相关的信息。

1、当前游戏版本 0.9.27.15033 mod试过上一版本0.0016和最新0.017，尝试0.0.16是因为经过断网后就无法 启用游戏里mod界面，就下了一个旧版本尝试，这次启动是能通过ctrl+F 启动界面，但是在重新开游戏后再次失效了（后续依旧失效）。

2、尝试过git更新到最新版r2modman,也删除了r2modmanPlus-local\DysonSphereProgram\整个文件夹，重新下载安装mod，重装过游戏。

3、尝试过覆盖别人正常的整个r2modmanPlus-local\DysonSphereProgram\profiles\Default文件夹，别人正常我还是同样无法使用

4、该问题是在我更换22h2系统以及游戏更新前后出现的，目前也没看见别的同样案例。

目前安装的mod列表(已经试过单开)：
Dependency string list

ebkr-r2modman-3.1.27
xiaoye97-BepInEx-5.4.17
CommonAPI-DSPModSave-1.1.4
xiaoye97-LDBTool-2.0.6
CommonAPI-CommonAPI-1.5.6
PhantomGamers-IlLine-1.0.0
nebula-NebulaMultiplayerModApi-1.3.1
nebula-NebulaMultiplayerMod-0.8.12
aekoch-UnlimitedFoundations-1.0.2
kremnev8-BlueprintTweaks-1.5.7
hetima-SplitterOverBelt-1.1.3
testpushpleaseignore-Planet_Vein_Utilization-1.0.5
starfi5h-BulletTime-1.2.10
jinxOAO-SmartTank-1.1.3
Klarkxy-IntelligentTransport-1.0.2
PhantomGamers-AchievementsEnabler-1.4.0
crecheng-Tp-2.1.0
crecheng-CloseError-1.0.0
Small-TransferInfo-1.1.2
blacksnipebiu-Multfuntion_mod-2.6.2
kremnev8-RebindBuildBar-1.0.3
kremnev8-BetterMachines-1.1.3
Acceyuriko-EnableAchievements-1.0.7
blacksnipebiu-MoreStatInfo-1.3.4
blacksnipebiu-Auxilaryfunction-1.8.8
hetima-ProductionLineCount-1.1.1
hetima-NoHidingManualResearch-1.0.0
hetima-ExpandTouchableRange-1.0.1
starfi5h-NebulaCompatibilityAssist-0.1.10
IndexOutOfRange-DSPTransportStat-0.0.17
appuns-DSPRecipeFinder-0.0.4
starfi5h-ReorderTechQueue-1.1.1
jinxOAO-InfiniteSpray-1.0.1
jinxOAO-SuperOrbitalCollectors-1.1.1
Allz-EnableMilkyWayGalaxy-1.1.7
appuns-DSPMarker-0.0.6

请求分析一下如何排错，谢谢

**Comment by LittleSaya** [comment]
我还没有测试过用除了Thunderstore Mod Manager之外的mod管理器来运行自己的mod，我晚上回去看一看，可能是因为游戏更新了吧，我有段时间没有更新mod了

**Comment by LittleSaya** [comment]
我还没有测试过用除了Thunderstore Mod Manager之外的mod管理器来运行自己的mod，我晚上回去看一看，可能是因为游戏更新了吧，我有段时间没有更新mod了

**Comment by NAGATOYUKl** [comment]
2023年1月10日最新进展，目前好了，可能是我的电脑新系统有问题。
1、CommonAPI-DSPModSave-1.1.4 这个mod据一起玩的小伙伴说是分开储存存档的功能，然后他给我指出在 C:\Users\[userID]\Documents\Dyson Sphere Program\Save\modData\IndexOutOfRange.DSPTransportStat 目录下有个 config.txt ，他的里面是有"True",而我的是空白，然后我补上"True"之后就能正常打开mod界面了。

之前因为笔记本过热系统强制关机过几次，不知道是不是因为这个导致的。

所以目前应该暂时排除问题了，后续有情况我会再反馈，感谢开发

![1673358779145](https://user-images.githubusercontent.com/42117627/211571616-ac239b5e-fb7c-4d67-b63e-53e792d31117.jpg)

**Comment by LittleSaya** [comment]
问题解决了就好，其实我还没看这个问题呢，工作日太忙了😂

**Comment by NAGATOYUKl** [comment]
理解理解，我也白天上班，晚上不加班就抽空联机耍耍，所以每次联机玩到一定进度，官方一更新存档就废了。
对了，现在非主机要在星系内都到访一次才能正常访问物流塔，不知道是不是游戏机制的限制，以及不通过一次筛选再取消筛选是看不全所有物流塔。也就一提，不作意见哈哈，继续加班XD

**Comment by LittleSaya** [comment]
> 理解理解，我也白天上班，晚上不加班就抽空联机耍耍，所以每次联机玩到一定进度，官方一更新存档就废了。
> 对了，现在非主机要在星系内都到访一次才能正常访问物流塔，不知道是不是游戏机制的限制，以及不通过一次筛选再取消筛选是看不全所有物流塔。也就一提，不作意见哈哈，继续加班XD

我估计不太兼容那个联机mod
