### ISSUE TITLE
一个小问题，关于部分物流塔显示不全

### ISSUE THREAD

**Issue by Aebestach** [LittleSaya/IndexOutOfRangeDSPMod#32]
刚启动游戏的时候，有些行星上的物流塔没有显示出来，需要筛选下物品后，再次取消，才可以正常显示。

**Comment by LittleSaya** [comment]
如果可以的话方便提供一下开启的mod和存档文件吗？我使用沙盒模式测试了一下，似乎没有遇到这个问题
