### ISSUE TITLE
Galactic Scale compatability

### ISSUE THREAD

**Issue by itpropro** [LittleSaya/IndexOutOfRangeDSPMod#33]
In Galactic Scale, I can't see the "Add planet" button. What is the alternative way to acquire the "UniqueStarId" fields?

**Comment by LittleSaya** [comment]
I'm afraid that this mod (AddPlanet) is not compatible with Galactic Scale, AddPlanet and Galatic Scale have some similar functionalities, they can both create planets with modified radius, this can make them conflict with each other.

**Comment by itpropro** [comment]
Galactic Scale wouldn’t “remember” the changes anyway, if AddPlanet doesn’t adjust the normal plus the GS2 save game file.
As that is probably a bit of work, the short term solution would be to document the incompatibility. I think GS already lists AddPlanet as incompatible.

**Comment by LittleSaya** [comment]
I tried to avoid re-patching functions that GS2 has patched, but things doesn't look as simple as I thought...Anyway, I uploaded a new version which will disable itself if it detects GS2.
