### ISSUE TITLE
运输船停靠问题

### ISSUE THREAD

**Issue by lixuancryo** [LittleSaya/IndexOutOfRangeDSPMod#6]
新添加的行星运输船均无法停靠。但原来自带的行星之间是可以正常停靠的。星球大小为200。

**Comment by LittleSaya** [comment]
无法停靠是指运输船到达目的物流站点以后一直悬停在物流站点旁边，但是不进去吗？

**Comment by LittleSaya** [comment]
无法停靠是指运输船到达目的物流站点以后一直悬停在物流站点旁边，但是不进去吗？

**Comment by lixuancryo** [comment]
对的。

**Comment by LittleSaya** [comment]
@lixuancryo 我试了一个半径200的行星，好像没有遇到这个问题。类似的问题我之前在半径400和600的行星上遇到过，当时是半径200的行星能正常停靠，半径400和600的行星不能正常停靠，不过那个问题现在已经修复了。方便发一下你配置新行星的字符串、摆放物流塔的位置和物流塔的配置吗？我用你的试试

**Comment by lixuancryo** [comment]
咱有邮箱啥的吗？我全发给你

**Comment by LittleSaya** [comment]
@lixuancryo littlesaya@outlook.com 这个

**Comment by LittleSaya** [comment]
@lixuancryo 收到了，被标记成垃圾邮件了。。我瞅瞅是啥原因

**Comment by LittleSaya** [comment]
@lixuancryo 你那边一共开了哪些mod方便也一起告诉我一下吗？我这边好像读不了存档

**Comment by LittleSaya** [comment]
@lixuancryo 不用了，我拿新档复现出来这个问题了，我研究一下

**Comment by lixuancryo** [comment]
好的好的。辛苦啦

**Comment by LittleSaya** [comment]
@lixuancryo 我更新了一下版本，应该修复了这个问题
