### ISSUE TITLE
加载存档报红字

### ISSUE THREAD

**Issue by lixuancryo** [LittleSaya/IndexOutOfRangeDSPMod#7]
您好！
我又遇到了新的问题 ;_; 相关信息已经发至邮箱！

**Comment by LittleSaya** [comment]
emm，我看见了，但是出问题的位置在游戏内部读取存档的地方，有点难以判断是什么导致了坏档。

DSPAddPlanet目前已知有一种情况会导致坏档，那就是造访过新的行星以后把新行星的配置删除，再读档就读不了了，你可以检查一下是不是有更改过那个config.txt文件。

这次坏档和DSPAddPlanet有关的地方我怀疑在那些有问题的运输船上，可能存档的时候它们消失了之类的。。

我先研究一下昨天的存档看一看

**Comment by LittleSaya** [comment]
另外还有一点，那就是手动保存存档的时候改名字等于把配置文件删掉。自动保存的时候存档的游戏名称是不会变的，但是手动保存的时候如果改名字，存档的游戏名称会变成新的名字，变成新的名字以后新增的行星还在存档里，但是读取存档和配置文件的时候会认为没有新的行星需要生成，所以也会红字。昨天我收到的存档是带有“-测试”后缀的，但是配置文件里是没有“-测试”后缀的（虽然我给配置文件里加上“-测试”后缀以后还是红字😥）。

这个“游戏名称”和存档的文件名称没有关系，如果在游戏里手动保存的时候写成“123”，存档的文件名也会是“123”，但是把文件名改成“456”不会让它的“游戏名称”也变成“456”

**Comment by lixuancryo** [comment]
只要造访过再删除就不行了吗？那我还真删过·····但是我只是上去看了一下，没修东西

**Comment by LittleSaya** [comment]
@lixuancryo 是的，造访以后就会初始化那个行星的工厂信息。。然后如果退出的时候保存正常的话，被造访的行星的工厂信息也会留在存档里。

如果还记得删掉的行星的配置的话，可以把配置还原

如果不记得配置，但是有造访之前的存档的话（如果有造访前的自动存档也行），可以试一下读取造访前的存档

**Comment by LittleSaya** [comment]
> @lixuancryo 是的，造访以后就会初始化那个行星的工厂信息。。然后如果退出的时候保存正常的话，被造访的行星的工厂信息也会留在存档里。
> 
> 如果还记得删掉的行星的配置的话，可以把配置还原
> 
> 如果不记得配置，但是有造访之前的存档的话（如果有造访前的自动存档也行），可以试一下读取造访前的存档

但是行星的样貌好像又和行星的数量、位置有关系，如果删除的行星在配置文件的中间，可能会导致在它后面新增的行星的样貌发生变化，具体的原理我还没有搞懂，使用时还是需要谨慎一些，我目前玩这个mod只在需要一个新的行星的时候才增加一个新的行星，然后在增加新行星之前手动存档一下，这样稍微稳妥一点，出问题可以及时读取自动存档或者手动存档

**Comment by lixuancryo** [comment]
噢~原来是这样！好的，谢谢！！
