### ISSUE TITLE
行星半径小于200

### ISSUE THREAD

**Issue by lixuancryo** [LittleSaya/IndexOutOfRangeDSPMod#8]
行星半径小于200时，它周围会有一个框。总之显示就不对，我也不知道该咋描述

**Comment by LittleSaya** [comment]
emm，好像是隐隐约约有一个白颜色的圆，似乎是大气的视觉效果，我看一看是不是哪里和半径相关的地方还没有改过来

**Comment by lixuancryo** [comment]
这是隐隐约约吗？我看着超明显！

**Comment by LittleSaya** [comment]
@lixuancryo 你说的是像这种包围行星的圆圈吗？可能是我添加的行星是贫瘠行星，大气层不太明显，我刚刚提交了一个新版本，这个圆圈应该会跟着行星的实际半径走了

<img width="563" alt="circle1" src="https://user-images.githubusercontent.com/16049823/169676694-7c79fead-bafa-4aba-a012-10d6412c3d6b.png">
<img width="275" alt="circle2" src="https://user-images.githubusercontent.com/16049823/169676695-5c83ba18-15ef-4135-8a8f-32ceb25df3d2.png">
<img width="257" alt="circle3" src="https://user-images.githubusercontent.com/16049823/169676697-84e352a7-4905-43ad-af23-bc82f9e11dc7.png">

**Comment by lixuancryo** [comment]
没有问题了！
